services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: library-server
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  
  db:
    image: postgres
    container_name: library-db
    restart: always
    networks:
      - library
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - library

volumes:
  dbdata:

networks:
  library: